### ISSUE TITLE
Cannot find symbol class PilotSyncer

### ISSUE THREAD

**Issue by IgorGanapolsky** [doridori/Pilot#37]
Hello,
Trying your PilotExample.  I am compiling against your latest Pilot lib `com.kodroid:pilot:0.9.0-SNAPSHOT`.  I am getting a build error in Android Studio 2.2 Preview 6 from ExampleRootActivity.java:

> Error:(15, 37) error: cannot find symbol class PilotSyncer

**Comment by doridori** [comment]
Hi,

Try 0.10.0_SNAPSHOT. Also test if you get the same error with `gradle
build` as I find sometimes Android Studio has caching issues when
dependencies are updated which can result in symbol errors.

**Comment by IgorGanapolsky** [comment]
> Failed to resolve: com.kodroid:pilot:0.10.0_SNAPSHOT

But **0.10.0-SNAPSHOT** works.  However, still the same compilation error.  Tried building from command line as well.

**Comment by doridori** [comment]
First of all, sorry for the confusion - I wrote the wrong symbol for the snapshot - as you point out its an `-` not `_`. Thats what I get from trying to resolve issues in the middle of the night!

I see now from a second look that you are using `ExampleRootActivity.java` so Im guessing your using the example app. This is quite out of date and I need to update it. As can be seen from the build file this was based on `0.4.6` and there have been a few breaking changes since then. Im finding that Im iterating versions quite quickly at present as the more I use it the more it makes sense to move things around and do things in better ways. 

At present, the most up-to-date docs are the https://github.com/doridori/Pilot/blob/master/docs/quick_start.md and https://github.com/doridori/Pilot/blob/master/docs/example_frame_and_view.md.

Sorry for the confusion - I will update the docs soon, all my extra time has been used on the functional changes so far!
